# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: 'Navigating the UI'
  link: '/navigating-the-ui'
- label: 'Widgets'
  items:
    - label: 'Introduction'
      link: '/widgets/introduction'
    - label: 'Config'
      link: '/widgets/config'
    - label: 'Layout'
      link: '/widgets/layout'
    - label: 'Styles'
      link: '/widgets/styles'
    - label: 'Events'
      link: '/widgets/events'
- label: 'Components'
  items:
    - label: 'Introduction'
      link: '/components/introduction'
    - label: 'Writing components in React'
      link: '/components/react'
    - label: 'Building components from widgets'
      link: '/components/widgets'
- label: 'Variables'
  items:
    - label: 'Introduction'
      link: '/variables/introduction'
    - label: 'Static variables'
      link: '/variables/static'
    - label: 'Function variables'
      link: '/variables/function'
    - label: 'Lookup variables'
      link: '/variables/lookup'
- label: 'Connecting to an API'
  items:
    - label: 'Introduction'
      link: '/api/introduction'
    - label: 'Fast API'
      link: '/api/fast-api'
    - label: 'Custom'
      link: '/api/custom'
- label: 'Templates'
  items:
    - label: 'Using templates'
      link: '/templates/using'
    - label: 'Creating templates'
      link: '/templates/creating'
- label: Usage
  items:
    - label: 'Creating docs'
      link: '/usage/creating-docs'
    - label: 'Navigation'
      link: '/usage/navigation'
    - label: 'Shadowing'
      link: '/usage/shadowing'
- label: More
  items:
    - label: FAQ
      link: /faq
    - label: 'Github'
      link: https://github.com/neb42/ui-studio
