name: Deploy patch 

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  deploy-patch:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
      - name: Check npm auth 
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build + deploy
        run: yarn deploy:patch:ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Deploy docs 
        run: yarn deploy:docs